### PR TITLE
Order by build id instead of last modified

### PR DESCRIPTION
**Pull request by alfredodeza**
Otherwise the UI presents builds that just got updated that have nothing to do with the latest push

### CODE REVIEW

**Comment by andrewschoen** [comment]
jenkins test this please

**Comment by alfredodeza** [comment]
jenkins test this please

**Comment by alfredodeza** [comment]
ceph-build seriously broken, needs: https://github.com/ceph/ceph-build/pull/792

**Comment by alfredodeza** [comment]
tox tests pass locally for these changes

**Comment by alfredodeza** [comment]
jenkins test this please

**Pull request merged**
