### PR TITLE
api/builds: Send email when build is completed

### PR DESCRIPTION
**Pull request by VallariAg**
[WIP] TODO: Add information (in the emails) about necessary builds required for scheduling.

Receive emails for testing with `python -m smtpd -c DebuggingServer -n localhost:1025`

Signed-off-by: Vallari Agrawal <val.agl002@gmail.com>

### CODE REVIEW

**Comment by dmick** [comment]
Surely there's a way for Jenkins to notify you when a build is done?

**Comment by VallariAg** [comment]
@dmick Can you help me with how I can go about that?

**Comment by dmick** [comment]
First, Google "Jenkins notifications"

**Comment by kamoltat** [comment]
@VallariAg Here is a link I found that might be useful: https://plugins.jenkins.io/email-ext/

@dmick I never worked on Jenkins before but I think in order for Vallari to set up Jenkins notifications, she will need admin access to modify the system configurations to set up the plugin and make changes to the pipeline script right?

**Comment by dmick** [comment]
In a little bit of poking, I've found a "post-build action" for sending email notifications that's already enabled, suggesting that it's a build job configuration option.  I have tested that the jenkins server is set up to send email and have sent myself a test email, so that administration is done already.

I see this, in jenkins-job-builder, what we use to manage the jobs: https://jenkins-job-builder.readthedocs.io/en/latest/publishers.html?highlight=email%20notification#publishers.email

**Comment by dmick** [comment]
Okay, so the builtin "email notification" post-build action works, but has a few limitations:

1) it only notifies about failed builds
2) it *must* notify a fixed address, and can optionally notify the github author

The "Email Extension" plugin is significantly more flexible, and I'd like to install it, not just for your needs in Shaman, but I think many projects would benefit.  But I need to coordinate with @djgalloway for a Jenkins reboot time, as other plugins need update to allow it.  Documentation is here, so you can see what's available:  https://plugins.jenkins.io/email-ext/

**Comment by kamoltat** [comment]
@dmick sounds good, I think that's the route we want to take. Please keep us updated on the installation so that @VallariAg can proceed with this PR. Thank you.

**Comment by dmick** [comment]
Planning on restarting Jenkins tonight.  Will advise when complete.

**Comment by dmick** [comment]
Jenkins is restarted and the email-ext plugin is available.  Here's a test section from a jenkins-job-builder job I created just to test the plugin.  You may not want all these options.  There are also options to set the subject and body, with token substitution; see the plugin docs and the jenkins job builder docs.

    publishers:
        - email-ext:
            content-type: html
            subject: 'dmick-test-notifications build ${BUILD_NUMBER}'
            failure: True
            success: True
            send-to:
              - developers
              - requester
              - upstream-committers

**Comment by dmick** [comment]
So the email extension has been installed on Jenkins and is usable; are you still interested in email notifications, @VallariAg ?

**Comment by VallariAg** [comment]
@dmick Instead of email notifications, we came up with another solution: a feature that allows users to queue teuthology commands to be executed automatically when a build is ready. So people can push to ceph-ci to queue builds and then queue a run in teuthology-api to be auto-scheduled when the build is ready. Jenkins can send a notification to teuthology-api (like it does to shaman) with the updated status, and teuthology-api can executed all queued teuthology-suite commands waiting for that build to be done. This kind of notification can automate a little part of that process.
This is a flow graph of implementation details: https://www.figma.com/board/hQg7eaBOk21KGdYbiO1PBm/auto-schedule?node-id=0-1

**Pull request closed without merging**
